"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier) — E2E.

Only the task-specific prose and stage cells live here. Runtime install, the embedded pipeline module
(``src/lmpipeline/pipeline.py``) and the base-model pin/stage/verify cell are produced by the generator
from repository sources so they cannot drift from the package. The QLoRA training loop is deliberately
kept as plain PyTorch template cells (every step visible) and consumes only the carried module's API.
The ARTIFACT-INFERENCE companion has its own template, ``tools/notebook_template_artifact_inference.py``.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

REPO = "language-model-pipeline"
BADGES = [
    (
        "GitHub",
        "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
        f"https://github.com/kurtvalcorza/{REPO}",
    ),
    (
        "Open In Colab",
        "https://colab.research.google.com/assets/colab-badge.svg",
        f"https://colab.research.google.com/github/kurtvalcorza/{REPO}/blob/main/tutorials/language_model_finetuning_colab.ipynb",
    ),
    (
        "Hugging Face",
        "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-HuggingFaceTB%2FSmolLM2--360M--Instruct-ffcc4d?style=flat",
        "https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct",
    ),
    (
        "Upstream",
        "https://img.shields.io/badge/Upstream-huggingface%2Fsmollm-181717?style=flat&logo=github&logoColor=white",
        "https://github.com/huggingface/smollm",
    ),
    ("arXiv", "https://img.shields.io/badge/arXiv-2502.02737-b31b1b.svg", "https://arxiv.org/abs/2502.02737"),
]

TEMPLATE = {
    "package": "lmpipeline",
    "repo_name": REPO,
    "stem": "language_model_finetuning",
    "notebook_name": "language_model_finetuning_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "isolated_runtime": True,
    "infrastructure_labels": True,
    # The fleet's uv isolated-environment mechanism (bioclip2-biodiversity-pipeline, siglip-v1-zero-shot-pipeline): a
    # managed CPython, a size- and SHA-256-verified uv wheel, and a lock compiled from the pyproject pins with
    # `uv pip compile pyproject.toml --python-version 3.12 --python-platform x86_64-manylinux_2_28 --generate-hashes
    # --only-binary :all: -o tutorials/requirements-isolated.lock.txt`. (tutorials/requirements-colab.lock is the older,
    # separate runtime declaration read by lmpipeline.tutorial_api; it is not what the notebooks install.)
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-isolated.lock.txt",
    "run_all": (
        "This notebook needs a CUDA runtime (Colab: Runtime > Change runtime type > T4 GPU) — it stops with a clear message otherwise (RUN11). Once that runtime is selected, **Run all** builds an isolated environment from the hash-locked pins (nothing is installed into the notebook's own Python, so no restart is needed and Run all completes in one pass), stages and digest-verifies the pinned base snapshot, fetches the pinned public Filipino SFT tutorial sample from the Hugging Face Hub at an immutable dataset revision (`SAMPLE_LIMIT` = 120 rows), validates the train/eval splits into an input manifest, renders and masks the chat template, records a deterministic pre-adaptation baseline, scores the unadapted base model on the validation split, attaches LoRA adapters and trains for one bounded epoch with the stated hyperparameters (QLoRA, seed 42), evaluates loss/perplexity base vs adapted as optimisation evidence only, generates for new prompts with the adapter off and on, exports the adapter bundle with its manifest and provenance, and reloads it from disk against the pinned base revision, reporting which numbers the reloaded artifact reproduces. No repository clone, DIMER worker or service, credential, upload dialog or configuration edit is required (NOTEBOOK_SPEC 2.2 §5)."
    ),
    "byod": (
        "After the sample workflow completes, set `USE_BYOD = True` in Section 4 and re-run from that cell to upload your own chat-format JSONL; it enters the same validation, split, masking, LoRA adaptation, evaluation, generation and export cells as the sample (DAT14). Expected schema, ceilings and privacy guidance are stated in the Prerequisites and in Section 4; the upload stays inside this runtime. BYOD is optional and never part of the default path."
    ),
    "guided": {
        "opening": [
            (
                "**Who this notebook is for.** A learner who knows basic Python, has run a Colab notebook, and wants to adapt an open instruction-tuned language model to their own conversations with QLoRA on a free T4 GPU — and to see exactly which tokens are trained, what the loss numbers do and do not mean, and how the adapter is shipped and reloaded. No transformer internals are assumed: *LoRA*, *QLoRA*, *chat template*, *loss masking* and *perplexity* are explained where they first matter and again in the **Glossary** at the end. A CUDA GPU is required (a Colab T4 is enough). The intended audience is learners and practitioners trying QLoRA for the first time; this is a teaching run, not a production fine-tuning recipe.\n\n**Input → Model → Output.**\n\n| | What it is in this notebook |\n|---|---|\n| Input | 120 chat-formatted conversations (default: the pinned public Filipino Q&A sample, 96 for training and 24 held out; BYOD: your `train.jsonl` with optional validation and test files) and the training knobs in Section 4 |\n| Model | the pinned SmolLM2-360M-Instruct base frozen in 4-bit `nf4`, plus small trainable LoRA matrices on the attention and MLP projections, trained by a plain PyTorch loop with assistant-only loss |\n| Output | an adapter bundle (LoRA weights, tokenizer, metrics, provenance, a SHA-256 manifest) and its ZIP; validation loss and perplexity of the base model and of the adapter (plus train loss per epoch); base versus adapted answers; a reload check that says what the artifact reproduces; an evaluation report; a result JSON and a probe CSV |\n\n**How to use this notebook.** Choose **Runtime → Change runtime type → T4 GPU**, then **Runtime → Run all**. Run all completes in one pass: Section 1 installs nothing into the notebook's own Python, so no restart is needed. Sections 1–3 are **infrastructure** — the isolated environment, the carried pipeline module and the pinned base snapshot — and their cells are collapsed; you may run them without studying them. The learning path starts in Section 4. Form fields (`# @param`) are the knobs: change one and re-run from that cell down. Re-running Section 6 or 7 starts again from the frozen base model, so a baseline is never taken from an adapted model and a second training run never stacks on the first; after a full run the trained model stays in memory, so Section 9 (`CUSTOM_PROMPT`) and the optional decoding activity can be re-run on their own. Before each principal result the notebook asks you to **Predict**; after it come **What to notice** and a collapsible **Check your reasoning**. No passing clean-run record exists yet for this notebook (`tutorials/RELEASE_VERIFICATION.md`): the only recorded run (Kaggle T4, 2026-09-14) was of an earlier revision that still installed into the kernel and needed a restart. Where the prose quotes its numbers it says so; the worked answers state what the code guarantees and what to expect qualitatively — compare them with your own run. **Troubleshooting**, a **Glossary** and a **Conclusion** template are at the end. Writing your predictions down is optional.\n\n**Roadmap:** 1–3 infrastructure → 4 knobs and data (or bring your own) → 5 validation, chat template and assistant-only loss masking *(core concept)* → 6 a deterministic baseline: base answers and base validation loss *(evaluation practice)* → 7 LoRA adapters and the training loop *(core concept)* → 8 the evaluation report: optimisation evidence, not task quality *(evaluation practice)* → 9 new prompts with the adapter off and on, plus an optional greedy-versus-sampling activity → 10 export the adapter bundle and check what a fresh reload reproduces *(engineering)* → interpretation, troubleshooting, glossary, conclusion."
            )
        ]
    },
    "carrier_note": (
        "**What matters for this notebook.** The parts this notebook exercises are, in order: `verify_snapshot` / `stage_missing_files` "
        "(Section 3), `canonical`, `manufacture_validation` and `validate_inputs` (Sections 4–5), `LanguageModelPipeline.prepare_splits`, "
        "`show_supervision`, `generate`, `evaluate_loss` and `to_batch` (Sections 5–7), `evaluation_report` (Section 8), and "
        "`export_adapter_bundle`, `reload_base` and `load_adapter` (Section 10). `validate_prompts`, `extract_zip_safely` and "
        "`verify_artifact_bundle` are the companion notebook's tools and also run inside `load_adapter`."
    ),
    "pipeline_class": "LanguageModelPipeline",
    "weights_key": "smollm2-360m",
    # generator /2: only the tutorial pipeline module is carried. The rest of `lmpipeline` (DIMER
    # worker contract, registry loader, result schema) is not needed by the notebook.
    "modules": ["pipeline.py"],
    "entry_module": "pipeline.py",
    "runtime_imports": ["torch", "transformers"],
    "title": "Language-Model Fine-Tuning — DIMER E2E QLoRA tutorial (standalone)",
    "badges": BADGES,
    "capability": "supervised QLoRA fine-tuning of the pinned `HuggingFaceTB/SmolLM2-360M-Instruct` base model on chat-formatted data, with baseline comparison, adapter export and fresh reload",
    "intro": (
        "You have a few hundred conversations from your own domain (this notebook ships with Filipino Q&A pairs) and an "
        "open, instruction-tuned language model that answers in the wrong language, register or format. Full fine-tuning "
        "would need tens of gigabytes of GPU memory and a multi-gigabyte copy of the weights for every variant you try. With "
        "**QLoRA** you adapt the base model on a free Colab T4, ship a compact **PEFT adapter** instead of another full "
        "base-model copy, and prove the adapter loads cleanly before anyone deploys it.\n\n"
        "**What is trained and what is not.** The base model is frozen in 4-bit `nf4`; only low-rank adapter matrices are "
        "gradient-trained (about one percent of the parameters). No preprocessing state is fitted: the chat template "
        "and tokenizer come from the base snapshot unchanged. Every base model in the carried registry is already "
        "instruction-tuned, so fine-tuning on ~100 rows shifts *how* it answers, not *whether* it can; expect subtle changes "
        "and some forgetting if you train hard. The carried module supplies the pinned identity, snapshot verification, "
        "dataset normalisation and hygiene, assistant-only loss masking, greedy generation, the adapter-bundle contract and "
        "the `validate_inputs` / `evaluation_report` helpers; the training loop below is plain PyTorch on purpose.\n\n"
        "**Which base model.** This standalone notebook pins **one** base model, `smollm2-360m` (the smallest entry in the "
        "repository's registry, chosen so the download, baseline, training and reload cycle stay short). The other registry "
        "entries (`TUTORIAL_REGISTRY` in the carried module — Qwen3, SmolLM3, Granite, DeepSeek-R1-Distill, "
        "Qwen2.5-Coder, danube3 and the gated `llama-3.2-3b-instruct`) are listed for reference: they are exercised by the "
        "repository's DIMER worker, and switching this tutorial to one of them means regenerating it from a template that "
        "pins that key, not editing a dropdown. No Hugging Face token is needed for the pinned model."
    ),
    "learning_objectives": (
        "install the pinned runtime, read what the carried pipeline module guarantees, resolve and digest-verify the "
        "immutable base snapshot, normalise instruction data from three common schemas into chat turns and validate it into "
        "an input manifest (leakage and over-length rows are rejected before training), mask the loss to assistant tokens "
        "using the model's own chat template and say exactly which tokens are supervised, record a deterministic "
        "pre-adaptation baseline (greedy answers and the base model's validation loss), run a one-epoch QLoRA loop you can read line by line, read base and adapted validation loss and "
        "perplexity as optimisation evidence rather than task quality, produce an evaluation report, compare base and adapted "
        "answers on new prompts, export a manifested adapter bundle, and check what a fresh reload against the verified base snapshot reproduces."
    ),
    "exclusions": (
        "full-parameter fine-tuning, preference tuning (RLHF/DPO), merging the adapter into 16-bit weights, task-quality "
        "evaluation (validation loss and perplexity measure format fit on a manufactured split, **not** whether answers are "
        "correct), serving, and any base model other than the pinned `smollm2-360m` snapshot."
    ),
    "prerequisites": [
        "- **Runtime:** a Colab GPU runtime (*Runtime ▸ Change runtime type ▸ T4 GPU*) or another CUDA machine; QLoRA needs `bitsandbytes` 4-bit kernels, so the training cell stops on CPU. Python 3.12 is the executed configuration. Section 1 builds a separate environment from the hash-locked pins (nothing is installed into the notebook's own Python, so no restart is needed); its PyTorch CUDA wheels are the largest download of the run.",
        "- **Knowledge:** Python functions, dictionaries and list comprehensions; what a language model does at a high level (predicts the next token). Transformer internals are not required.",
        "- **Data:** the default sample is the pinned public `jpaulpoliquit/ph-sft-ai-authored-v1` table (513 AI-authored Filipino/English Q&A rows, Apache-2.0), fetched from the Hugging Face Hub at an immutable dataset revision; `Sample: Dolly` (`databricks-dolly-15k`, CC-BY-SA 3.0 — adapters trained on it inherit the share-alike condition) is the alternative. Optional BYOD is gated off by default so the sample path runs top-to-bottom without interaction; it reads a folder or ZIP from `BYOD_PATH` (Kaggle, Jupyter) or, when that is empty on Colab, the upload dialog. Expected BYOD input: `train.jsonl` (plus optional `validation.jsonl`/`val.jsonl` and `test.jsonl`), each line a `messages`, `prompt`/`completion` or `instruction`/`input`/`output` record, uploaded as files or one ZIP. Do not upload confidential or restricted data to a hosted notebook environment unless you are authorized to do so. Uploaded inputs remain in the notebook runtime; this pipeline does not send them to a third-party inference API.",
    ],
    "cells": [
        {
            "md": (
                "## 4. Choose the knobs and load the sample or optional BYOD\n\n"
                "The carried module pinned the base model in Section 3 and loaded it in 4-bit **NormalFloat (`nf4`)** with "
                "double quantization: a 360M model drops from ~0.7 GB of 16-bit weights to well under 0.3 GB, and the frozen "
                "weights are dequantized on the fly to the compute dtype — bfloat16 whenever `torch.cuda.is_bf16_supported()` is true, which includes a T4 (emulated; the recorded run reports `bfloat16` on a Tesla T4), float16 otherwise — for "
                "each matrix multiply. The cell first confirms a CUDA device is present (QLoRA needs it) and prints the "
                "registry ceilings before any data is touched.\n\n"
                "Supervised fine-tuning needs conversations, not rows. Whatever the source schema — chat `messages`, "
                "`prompt`/`completion` pairs, or Alpaca-style `instruction`/`input`/`output` records (the two shipped samples are "
                "Alpaca-shaped) — `canonical` normalises every example to `{{\"messages\": [{{role, content}}, ...]}}`. For a shipped "
                "sample the notebook walks the rows in a deterministic hash order, keeps the first `SAMPLE_LIMIT` that fit "
                "within `MAX_SEQUENCE_LENGTH` **tokens** (measured with the base tokenizer through `pipe.token_length`), and "
                "holds out one fifth as validation with `manufacture_validation`. That validation split is *manufactured from "
                "the training source*: its loss is an optimisation signal, not a task-quality measurement. BYOD files are "
                "read as JSONL; a `validation.jsonl` is used when present, otherwise a fifth of `train.jsonl` is held out. Look "
                "for the split sizes (`{{'train': 96, 'validation': 24}}` with the defaults) and the 16-character dataset "
                "digest prefix — the identity of this exact dataset.\n\n"
                "For BYOD, set `BYOD_PATH` to a folder holding `train.jsonl` (plus optional `validation.jsonl`/`val.jsonl` and "
                "`test.jsonl`) or to one ZIP of them (Kaggle, Jupyter); leave it empty on Colab to get the upload dialog. A "
                "cancelled upload, a runtime without the dialog, a missing `train.jsonl` and a malformed JSONL line are refused "
                "with a message naming the file, the line and the rule. When no validation file is given, the training rows are "
                "put into the same deterministic hash order as the sample before one fifth is held out, so a topic-sorted file "
                "still yields a mixed validation set. A BYOD row longer than `MAX_SEQUENCE_LENGTH` tokens is **not** set aside "
                "the way sample rows are: `validate_inputs` in Section 5 rejects the dataset and names the row, so shorten or "
                "remove it (or raise the knob, within the ceiling).\n\n"
                "**Predict:** with the defaults (`SAMPLE_LIMIT` = 120), how many rows will land in each split?\n\n"
                "<details><summary>Check your reasoning</summary>\n\n"
                "`manufacture_validation` holds out one fifth, so 120 collected rows split into 96 for training and 24 for "
                "validation. If some sample rows are longer than `MAX_SEQUENCE_LENGTH` tokens the cell reports how many it set "
                "aside, but it keeps walking until it has 120 that fit, so the split sizes do not change.\n\n"
                "</details>"
            ),
            "code": (
                "import hashlib\n"
                "import io\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "# Kaggle / Jupyter: a folder holding train.jsonl (+ optional validation/test files) or one ZIP. Empty: the Colab upload dialog.\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n"
                "DATA_SOURCE = \"Sample: Filipino SFT\"  # @param [\"Sample: Filipino SFT\",\"Sample: Dolly\"]\n"
                "SAMPLE_LIMIT = 120  # @param {{type:\"integer\"}}\n"
                "MAX_SEQUENCE_LENGTH = 512  # @param {{type:\"integer\"}}\n"
                "EPOCHS = 1  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 0.0002  # @param {{type:\"number\"}}\n"
                "LORA_RANK = 8  # @param {{type:\"integer\"}}\n"
                "LORA_ALPHA = 16  # @param {{type:\"integer\"}}\n"
                "SEED = 42  # @param {{type:\"integer\"}}\n"
                "TRAINING_METHOD = 'qlora'\n\n"
                "if not torch.cuda.is_available():\n"
                "    raise RuntimeError('No GPU visible. In Colab: Runtime > Change runtime type > T4 GPU, then rerun from the top.')\n"
                "GPU_NAME = torch.cuda.get_device_name(0)\n"
                "GPU_VRAM_GB = torch.cuda.get_device_properties(0).total_memory / 1024**3\n"
                "print({{'ceilings': {{'MAX_SEQUENCE_LENGTH_CEILING': MAX_SEQUENCE_LENGTH_CEILING, 'MAX_TOTAL_TRAIN_TOKENS': MAX_TOTAL_TRAIN_TOKENS, 'MIN_TRAIN_EXAMPLES': MIN_TRAIN_EXAMPLES, 'MAX_NEW_TOKENS_CEILING': MAX_NEW_TOKENS_CEILING}}, 'request': {{'max_sequence_length': MAX_SEQUENCE_LENGTH, 'epochs': EPOCHS, 'learning_rate': LEARNING_RATE, 'lora_rank': LORA_RANK, 'lora_alpha': LORA_ALPHA, 'seed': SEED}}}})\n"
                "print({{'gpu': GPU_NAME, 'vram_gib': round(GPU_VRAM_GB, 2), 'quantized_4bit': pipe.quantized, 'compute_dtype': pipe.compute_dtype, 'source': pipe.source}})\n\n"
                "WORK_DIR = Path('work')\n"
                "shutil.rmtree(WORK_DIR, ignore_errors=True)\n"
                "WORK_DIR.mkdir()\n\n"
                "BYOD_FILES = ('train.jsonl', 'validation.jsonl', 'val.jsonl', 'test.jsonl')\n\n"
                "if USE_BYOD:\n"
                "    byod_root = WORK_DIR / 'byod'\n"
                "    byod_root.mkdir()\n"
                "    if BYOD_PATH.strip():\n"
                "        byod_source = Path(BYOD_PATH.strip()).expanduser()\n"
                "        if byod_source.is_dir():\n"
                "            for name in BYOD_FILES:\n"
                "                if (byod_source / name).is_file():\n"
                "                    shutil.copyfile(byod_source / name, byod_root / name)\n"
                "        elif byod_source.is_file() and byod_source.suffix.lower() == '.zip':\n"
                "            extract_zip_safely(byod_source, byod_root, size_limit_bytes=2 * 1024**3)\n"
                "        else:\n"
                "            raise FileNotFoundError(f'BYOD_PATH {{str(byod_source)!r}} is neither a folder nor a .zip file: give a folder holding train.jsonl (plus optional validation.jsonl/val.jsonl and test.jsonl) or one ZIP of them')\n"
                "    else:\n"
                "        try:\n"
                "            from google.colab import files\n"
                "        except ImportError:\n"
                "            raise RuntimeError('USE_BYOD = True but BYOD_PATH is empty and this runtime has no Colab upload dialog: set BYOD_PATH to a folder or ZIP holding train.jsonl') from None\n"
                "        uploaded = files.upload() or {{}}\n"
                "        if not uploaded:\n"
                "            raise RuntimeError('The upload was cancelled or empty: run this cell again and choose train.jsonl (plus optional validation/test files) or one ZIP, or set BYOD_PATH')\n"
                "        if len(uploaded) == 1 and next(iter(uploaded)).lower().endswith('.zip'):\n"
                "            zip_path = WORK_DIR / 'data.zip'\n"
                "            zip_path.write_bytes(next(iter(uploaded.values())))\n"
                "            extract_zip_safely(zip_path, byod_root, size_limit_bytes=2 * 1024**3)\n"
                "        else:\n"
                "            for name, payload in uploaded.items():\n"
                "                (byod_root / Path(name).name).write_bytes(payload)\n\n"
                "    def read_jsonl(path):\n"
                "        records = []\n"
                "        for number, line in enumerate(path.read_text(encoding='utf-8').splitlines(), start=1):\n"
                "            if not line.strip():\n"
                "                continue\n"
                "            try:\n"
                "                records.append(canonical(json.loads(line)))\n"
                "            except (ValueError, KeyError, TypeError) as exc:\n"
                "                raise ValueError(f'{{path.name}} line {{number}}: not a messages, prompt/completion or instruction/input/output record ({{type(exc).__name__}}: {{exc}})') from None\n"
                "        return records\n\n"
                "    if not (byod_root / 'train.jsonl').exists():\n"
                "        raise ValueError(f'BYOD requires train.jsonl at the top level of the folder or ZIP; found: {{sorted(p.name for p in byod_root.iterdir()) or \"nothing\"}}')\n"
                "    if (byod_root / 'validation.jsonl').exists() and (byod_root / 'val.jsonl').exists():\n"
                "        raise ValueError('Provide either validation.jsonl or val.jsonl, not both')\n"
                "    SPLITS = {{'train': read_jsonl(byod_root / 'train.jsonl')}}\n"
                "    validation_file = byod_root / ('validation.jsonl' if (byod_root / 'validation.jsonl').exists() else 'val.jsonl')\n"
                "    if validation_file.exists():\n"
                "        SPLITS['validation'] = read_jsonl(validation_file)\n"
                "    if (byod_root / 'test.jsonl').exists():\n"
                "        SPLITS['test'] = read_jsonl(byod_root / 'test.jsonl')\n"
                "    if 'validation' not in SPLITS:\n"
                "        # Same deterministic hash order as the sample path, so a topic-sorted file does not hold out one topic.\n"
                "        SPLITS = {{**SPLITS, **manufacture_validation(sorted(SPLITS['train'], key=fingerprint))}}\n"
                "    DATASET_PROVENANCE = {{'source': 'BYOD', 'usage': 'user-provided'}}\n"
                "    sample_kind = 'BYOD'\n"
                "    data_name = 'byod-jsonl'\n"
                "else:\n"
                "    from datasets import load_dataset\n\n"
                "    sample = SAMPLE_DATASETS[DATA_SOURCE]\n"
                "    all_rows = sorted((canonical(dict(row)) for row in load_dataset(sample['dataset_id'], revision=sample['revision'], split='train')), key=fingerprint)\n"
                "    rows, skipped_long = [], 0\n"
                "    for row in all_rows:\n"
                "        if len(rows) == SAMPLE_LIMIT:\n"
                "            break\n"
                "        if pipe.token_length(row) <= MAX_SEQUENCE_LENGTH:\n"
                "            rows.append(row)\n"
                "        else:\n"
                "            skipped_long += 1\n"
                "    if skipped_long:\n"
                "        print(f'Set aside {{skipped_long}} sample rows longer than {{MAX_SEQUENCE_LENGTH}} tokens while collecting {{len(rows)}}')\n"
                "    SPLITS = manufacture_validation(rows)\n"
                "    DATASET_PROVENANCE = {{'source': sample['dataset_id'], 'revision': sample['revision'], 'license': sample['license'], 'usage': 'tutorial-training-not-benchmark'}}\n"
                "    sample_kind = 'sample'\n"
                "    data_name = sample['dataset_id']\n\n"
                "DATASET_DIGEST = dataset_digest(SPLITS)\n"
                "print({{'sample_kind': sample_kind, 'name': data_name, 'splits': {{name: len(records) for name, records in SPLITS.items()}}, 'dataset_digest': DATASET_DIGEST[:16]}})\n"
                "print('First training example:')\n"
                "print(json.dumps(SPLITS['train'][0], ensure_ascii=False, indent=2)[:600])"
            ),
        },
        {
            "md": (
                "## 5. Validate the splits → input manifest, then render and mask\n\n"
                "`validate_inputs` is the pipeline's public validation stage: it applies exactly the checks "
                "`pipe.prepare_splits` applies — canonical records with valid roles and a non-empty assistant turn, at least "
                "`MIN_TRAIN_EXAMPLES` training rows, **no identical record in two splits** (leakage is fatal), exact duplicates "
                "inside a split reported as findings but not removed, every rendered example within `MAX_SEQUENCE_LENGTH` "
                "tokens and the training total within `MAX_TOTAL_TRAIN_TOKENS` — and returns an **input manifest** naming the "
                "schema, per-split record and token counts, the dataset digest and the verdict. It is written to "
                "`outputs/{stem}_input_manifest.json`. To show what rejection looks like, the cell also validates a "
                "deliberately leaked probe (a training row copied into validation) and records the pipeline's own error "
                "message as a finding.\n\n"
                "Then `pipe.prepare_splits` renders each conversation with the tokenizer's **chat template** and masks the "
                "loss: the model must not learn to *write the user's questions*, only to *answer them*, so every token outside "
                "an assistant turn gets the label `-100` (`IGNORE_INDEX`, which PyTorch's cross-entropy ignores). This is "
                "**assistant-only loss masking**, the single most common thing to get wrong in SFT. The assistant span starts "
                "exactly where the generation prompt ends — the same prompt the model sees at inference — and runs through the "
                "end-of-turn marker, so the model learns to stop. Over-length rows are rejected, never truncated. The last "
                "print decodes the first training example and wraps every supervised run in `⟦ ⟧`: the answer text and its "
                "end-of-turn marker are inside, the user turn and role markers are not.\n\n"
                "**Predict:** will the leaked probe be accepted? And in the decoded first example, which parts will sit inside `⟦ ⟧`?\n\n"
                "**What to notice:** `findings` (one rejection, with the pipeline's own message), the supervised-token counts "
                "against the total token counts per split, and the `⟦ ⟧` spans.\n\n"
                "<details><summary>Check your reasoning</summary>\n\n"
                "The probe is rejected: one validation row is identical to a training row, and leakage is fatal in "
                "`validate_inputs`, so its message is recorded under `findings` while the real splits are accepted. Inside "
                "`⟦ ⟧` you should see only the assistant's answer and its end-of-turn marker; the system and user turns and "
                "the role markers are outside, which is why the supervised-token count of each split is well below its total "
                "token count.\n\n"
                "</details>"
            ),
            "code": (
                "os.makedirs('outputs', exist_ok=True)\n"
                "input_manifest = validate_inputs(SPLITS, MAX_SEQUENCE_LENGTH, token_length=pipe.token_length, names=[f'{{data_name}}:{{name}}' for name in SPLITS])\n"
                "# Demonstrate rejection on a probe that leaks a training row into validation; the finding is recorded, not swallowed.\n"
                "probe = {{'train': SPLITS['train'], 'validation': [*SPLITS['validation'], SPLITS['train'][0]]}}\n"
                "try:\n"
                "    validate_inputs(probe, MAX_SEQUENCE_LENGTH)\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'leaked-split-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "print(json.dumps(input_manifest['inputs'], indent=2))\n"
                "print('findings:', input_manifest['findings'])\n\n"
                "MASKED = pipe.prepare_splits(SPLITS, MAX_SEQUENCE_LENGTH)\n"
                "token_totals = {{name: sum(len(ids) for ids, _ in examples) for name, examples in MASKED.items()}}\n"
                "supervised_totals = {{name: sum(supervised_token_count(labels) for _, labels in examples) for name, examples in MASKED.items()}}\n"
                "longest_train = max((len(ids) for ids, _ in MASKED['train']), default=0)\n"
                "if longest_train > 1024:\n"
                "    print(f'Notice: the longest training example is {{longest_train}} tokens; sequences above ~1024 raise peak VRAM noticeably.')\n"
                "print('tokens per split:', token_totals)\n"
                "print('supervised (assistant) tokens per split:', supervised_totals)\n"
                "print(show_supervision(pipe.tokenizer, *MASKED['train'][0]))"
            ),
        },
        {
            "md": (
                "## 6. Record a deterministic baseline\n\n"
                "You cannot see what training changed unless you record what the model said *before*. The two probe prompts "
                "are asked through `pipe.generate` with **greedy decoding** (`do_sample=False`, the module's `DECODING_RULE`) "
                "so the comparison after training is deterministic given the same weights, device and "
                "library versions. `generate` puts the model in eval mode (no dropout), turns the KV cache on, and restores "
                "whatever state it found, so the same helper is safe to call in the middle of training later. Look for two "
                "short answers; the unadapted base model may echo the Filipino prompt back almost verbatim (the recorded run did), "
                "answer in English, or mix the two.\n\n"
                "The cell also scores the **unadapted base model on the validation split** with `pipe.evaluate_loss` — the same "
                "function, the same 24 rows and the same per-supervised-token units that Section 7 uses after training. Without "
                "this number the adapted validation loss cannot be interpreted at all: it is the only way to tell whether one "
                "epoch lowered the loss, raised it, or did nothing.\n\n"
                "Sections 7 and 10 attach LoRA layers to the loaded model in place. If you re-run this section after them, the "
                "cell first reloads the frozen base from the verified snapshot (`pipe.reload_base`, no network) and says so, "
                "so the baseline is always the unadapted model.\n\n"
                "**Predict:** in which language will the base model answer the two Filipino prompts? Will the base validation loss be "
                "above or below the adapted validation loss Section 7 prints?\n\n"
                "<details><summary>Check your reasoning</summary>\n\n"
                "SmolLM2 is instruction-tuned mostly on English data, so an English or mixed answer is common — and so is an echo "
                "of the prompt, which is what the recorded Kaggle run printed for both prompts. Write down what it actually said: "
                "Section 7 asks the same prompts again, with greedy decoding, so any difference comes from the adapter. The "
                "direction of the loss change is not guaranteed; the usual outcome of one epoch on in-distribution rows is a lower "
                "adapted loss, and Section 7 prints the base → adapted line so you can see which way it went.\n\n"
                "</details>"
            ),
            "code": (
                "import gc\n\n\n"
                "def frozen_base():\n"
                "    \"\"\"The canonical model must be the frozen base: Sections 7 and 10 attach LoRA layers to pipe.model in place,\n"
                "    so a re-run of this section or of Section 7 first reloads the base from the verified snapshot (no network).\"\"\"\n"
                "    global model, reloaded\n"
                "    if any('lora_' in name.lower() for name, _ in pipe.model.named_modules()):\n"
                "        model = reloaded = None\n"
                "        pipe.model = None\n"
                "        gc.collect()\n"
                "        torch.cuda.empty_cache()\n"
                "        pipe.model = pipe.reload_base()\n"
                "        print('Reloaded the frozen base model from the verified snapshot: the loaded model carried LoRA adapters from an earlier run.')\n"
                "    return pipe.model\n\n\n"
                "frozen_base()\n"
                "PROMPTS = [\n"
                "    'Ipaliwanag sa simpleng Filipino kung ano ang machine learning.',\n"
                "    'Magbigay ng tatlong paraan para mabawasan ang basura sa opisina.',\n"
                "]\n"
                "print({{'decoding_rule': DECODING_RULE, 'max_new_tokens': 96, 'prompts': len(PROMPTS)}})\n"
                "BASELINE_OUTPUTS = [pipe.generate(prompt) for prompt in PROMPTS]\n"
                "for prompt, answer in zip(PROMPTS, BASELINE_OUTPUTS):\n"
                "    print(f'PROMPT: {{prompt}}\\nBASE:   {{answer}}\\n')\n"
                "# The unadapted base model scored on the same validation split, before any LoRA layer exists.\n"
                "BASE_VALIDATION_LOSS = pipe.evaluate_loss(MASKED['validation'])\n"
                "print({{'base_validation_loss': BASE_VALIDATION_LOSS, 'base_validation_perplexity': perplexity(BASE_VALIDATION_LOSS), 'rows': len(MASKED['validation'])}})"
            ),
        },
        {
            "md": (
                "## 7. Attach LoRA adapters and train\n\n"
                "**LoRA** keeps every original weight matrix $W_0$ frozen and learns a low-rank correction "
                "$W = W_0 + \\frac{{\\alpha}}{{r}} B A$ with $A$ of shape $r \\times d_{{in}}$ and $B$ of shape $d_{{out}} \\times r$. "
                "With rank $r = 8$ that is a few thousand numbers per layer instead of millions; $B$ starts at zero, so at step "
                "0 the adapted model *is* the base model, and $\\alpha / r$ scales the correction (the defaults give 2). "
                "Adapters go on both the attention projections (`q/k/v/o_proj`) and the MLP projections "
                "(`gate/up/down_proj`); attention-only LoRA is cheaper but adapts noticeably less. "
                "`prepare_model_for_kbit_training` does the QLoRA housekeeping: layer norms and the output head stay in "
                "32-bit for stable gradients through the 4-bit layers, and gradient checkpointing trades compute for memory. "
                "Expect **about 1.2 %** of the parameters to be trainable (the recorded run: 4 341 760 of 366 162 880, 1.186 %).\n\n"
                "The loop is deliberately plain PyTorch rather than a `Trainer`, so every moving part is visible: one example "
                "per forward pass and an optimizer step every two (`GRAD_ACCUM = 2`, an effective batch of 2 with no "
                "padding; the loss is scaled by the window size so the gradient matches a true batch), **AdamW at a constant "
                "learning rate** (no warmup or schedule — add one when you train for real), losses averaged **per supervised "
                "token**, and validation loss measured through `pipe.evaluate_loss` in eval mode with gradients off. Seeds "
                "control the shuffle; bitwise determinism across GPU kernels is not promised. Every epoch's train and validation "
                "loss is kept in `METRICS['epochs']`, and the cell ends with a **base → adapted** validation-loss line against the "
                "number Section 6 recorded. Afterwards the two probe prompts are asked again for the before/after table. For "
                "comparison only: the recorded Kaggle T4 run of an earlier revision of this notebook (2026-09-14, after a kernel "
                "restart that this revision no longer needs) printed train loss 3.266, validation loss 3.261, perplexity 26.1, "
                "55.5 s and 0.66 GiB peak with these defaults; your numbers will differ somewhat. Re-running this cell trains a new "
                "adapter on the frozen base (the cell reloads the base first if it already carries LoRA layers); it never "
                "trains on top of the previous adapter.\n\n"
                "**Predict:** what percentage of the parameters will be trainable? After one epoch, will the adapted validation loss "
                "be below the base validation loss from Section 6, and will it be above or below the training loss?\n\n"
                "**What to notice:** `trainable_percent`, the base → adapted validation-loss line, and whether the adapted answers "
                "changed language or register compared with the baseline.\n\n"
                "<details><summary>Check your reasoning</summary>\n\n"
                "About 1 %: rank-8 matrices on seven projection types are small next to 360 million frozen weights, though not "
                "\"a fraction of a percent\" — the recorded run printed 1.186 %. An adapted validation loss below the base one "
                "means the epoch moved the model towards the format of these rows; the amount is the interesting part, and no "
                "direction is guaranteed on your data. Validation loss at or slightly below training loss after one epoch is "
                "normal here — dropout is active while training, and the validation split is manufactured from the same source "
                "(Section 8 explains why that makes it optimisation evidence only); the recorded run showed exactly that pattern. "
                "The exact values depend on your GPU and run.\n\n"
                "</details>"
            ),
            "code": (
                "import gc\n"
                "import random\n"
                "import time\n\n"
                "from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training\n\n"
                "frozen_base()  # a re-run trains a fresh adapter on the frozen base, never on top of the previous one\n"
                "CANDIDATE_TARGETS = {{'q_proj', 'k_proj', 'v_proj', 'o_proj', 'gate_proj', 'up_proj', 'down_proj'}}\n"
                "LORA_TARGETS = sorted({{name.rsplit('.', 1)[-1] for name, _ in pipe.model.named_modules()}} & CANDIDATE_TARGETS)\n"
                "if not LORA_TARGETS:\n"
                "    raise RuntimeError('No LoRA target modules found; this architecture names its projections differently')\n"
                "lora_config = LoraConfig(r=LORA_RANK, lora_alpha=LORA_ALPHA, lora_dropout=0.05, bias='none', task_type='CAUSAL_LM', target_modules=LORA_TARGETS)\n"
                "model = get_peft_model(prepare_model_for_kbit_training(pipe.model), lora_config)\n"
                "trainable_params, all_params = model.get_nb_trainable_parameters()\n"
                "print({{'lora_targets': LORA_TARGETS, 'trainable_parameters': trainable_params, 'all_parameters': all_params, 'trainable_percent': round(100 * trainable_params / all_params, 3)}})\n\n"
                "GRAD_ACCUM = 2  # examples per optimizer step; batch size is 1, so this is the effective batch\n"
                "optimizer = torch.optim.AdamW([p for p in model.parameters() if p.requires_grad], lr=LEARNING_RATE)\n"
                "random.seed(SEED)\n"
                "torch.manual_seed(SEED)\n"
                "torch.cuda.reset_peak_memory_stats()\n"
                "started = time.time()\n"
                "EPOCH_LOSSES = []  # every epoch's losses are kept; the exported adapter is the LAST epoch's (no selection)\n"
                "for epoch in range(1, EPOCHS + 1):\n"
                "    model.train()\n"
                "    examples = MASKED['train'][:]\n"
                "    random.shuffle(examples)\n"
                "    optimizer.zero_grad()\n"
                "    epoch_loss, epoch_tokens, pending = 0.0, 0, 0\n"
                "    for step, example in enumerate(examples, start=1):\n"
                "        batch = pipe.to_batch(example, model)\n"
                "        outputs = model(**batch)\n"
                "        window = min(GRAD_ACCUM, len(examples) - (step - 1))  # the last window may hold a single example\n"
                "        (outputs.loss / window).backward()\n"
                "        count = supervised_token_count(example[1])\n"
                "        epoch_loss += outputs.loss.detach().item() * count\n"
                "        epoch_tokens += count\n"
                "        pending += 1\n"
                "        if pending == window:\n"
                "            optimizer.step()\n"
                "            optimizer.zero_grad()\n"
                "            pending = 0\n"
                "    train_loss = epoch_loss / epoch_tokens\n"
                "    validation_loss = pipe.evaluate_loss(MASKED['validation'], model=model)\n"
                "    EPOCH_LOSSES.append({{'epoch': epoch, 'trainLoss': train_loss, 'validationLoss': validation_loss, 'validationPerplexity': perplexity(validation_loss)}})\n"
                "    print(f'epoch {{epoch}}: train loss {{train_loss:.4f}} | validation loss {{validation_loss:.4f}}')\n\n"
                "model.eval()\n"
                "METRICS = {{\n"
                "    'baseValidationLoss': BASE_VALIDATION_LOSS,\n"
                "    'baseValidationPerplexity': perplexity(BASE_VALIDATION_LOSS),\n"
                "    'trainLoss': train_loss,\n"
                "    'validationLoss': validation_loss,\n"
                "    'testLoss': pipe.evaluate_loss(MASKED.get('test', []), model=model),\n"
                "    'validationPerplexity': perplexity(validation_loss),\n"
                "    'epochs': EPOCH_LOSSES,\n"
                "    'wallSeconds': time.time() - started,\n"
                "    'peakGpuMemoryBytes': torch.cuda.max_memory_allocated(),\n"
                "    'peakGpuMemoryGiB': torch.cuda.max_memory_allocated() / 1024**3,\n"
                "}}\n"
                "ADAPTED_OUTPUTS = [pipe.generate(prompt, model=model) for prompt in PROMPTS]\n"
                "probes = [{{'prompt': p, 'base': b, 'adapted': a}} for p, b, a in zip(PROMPTS, BASELINE_OUTPUTS, ADAPTED_OUTPUTS)]\n"
                "for row in probes:\n"
                "    print(f\"PROMPT:  {{row['prompt']}}\\nBASE:    {{row['base']}}\\nADAPTED: {{row['adapted']}}\\n\")\n"
                "print(f'validation loss base → adapted: {{BASE_VALIDATION_LOSS:.4f}} → {{validation_loss:.4f}} (change {{validation_loss - BASE_VALIDATION_LOSS:+.4f}} nats per supervised token; perplexity {{perplexity(BASE_VALIDATION_LOSS):.1f}} → {{perplexity(validation_loss):.1f}})')\n"
                "print(json.dumps(METRICS, indent=2))"
            ),
        },
        {
            "md": (
                "## 8. Evaluate → evaluation report\n\n"
                "`evaluation_report` is the pipeline's public evaluation stage and always produces a report. It carries the "
                "metrics the loop produced under the repository's own ids — `trainLoss`, `validationLoss`, `testLoss` when a "
                "test split exists, and `validationPerplexity` ($e^{{\\text{{loss}}}}$: how unsure the model was, on average, at "
                "each answer position) — and lists the Section 6 base-model numbers under `baselines` (`baseValidationLoss`, "
                "`baseValidationPerplexity`, same units, same rows), with the verdict `sample-sanity`: a single seeded run on a validation split "
                "manufactured from the training source, with no dispersion estimate. These are **optimisation** metrics; "
                "they say the adapter is fitting the *format* of the data and nothing about whether the answers are "
                "*correct*. **Task quality** needs a held-out set from your real task, a rubric and ideally human ratings, "
                "which the report names under `needs`; without a scored validation split the verdict is `not-measurable`. "
                "The base/adapted probe answers are recorded as qualitative evidence. The report is written to "
                "`outputs/{stem}_evaluation_report.json`. Validation loss slightly below training loss after one epoch is "
                "normal here (dropout is active during training and the splits share a distribution). With `EPOCHS = 3`, watch "
                "whether the validation loss keeps falling or turns up — an upturn is overfitting. This notebook records every "
                "epoch's losses in the result JSON but exports the **last** epoch's adapter and selects nothing: picking the "
                "lowest-validation-loss epoch would turn that loss into a selection metric on the same manufactured split, with "
                "no independent set left to report. Do epoch selection outside this notebook, against a held-out set from your "
                "real task.\n\n"
                "**Predict:** which verdict will the report give with the default sample?\n\n"
                "<details><summary>Check your reasoning</summary>\n\n"
                "`sample-sanity`: a validation split was scored, but it is one seeded run on a split manufactured from the "
                "training source, with no dispersion estimate. The base model's loss on the same split sits under `baselines`, "
                "so the report can be read as a change rather than a lone number. The `needs` field names what task quality "
                "would require — a held-out set from your real task, a rubric and ideally human ratings. `not-measurable` "
                "appears only when no validation split was scored.\n\n"
                "</details>"
            ),
            "code": (
                "report = evaluation_report(METRICS, sample_kind=sample_kind, n_train=len(SPLITS['train']), n_validation=len(SPLITS['validation']), probes=probes)\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(report, handle, indent=2, ensure_ascii=False)\n"
                "print(json.dumps({{k: v for k, v in report.items() if k != 'probes'}}, indent=2))\n"
                "if report['verdict'] == 'not-measurable':\n"
                "    print('No validation split was scored; the loop above produced no held-out loss.')"
            ),
        },
        {
            "md": (
                "## 9. Try new prompts with the adapter off and on\n\n"
                "The probe prompts above are the ones the model saw during evaluation. Real use means unseen instructions. "
                "The cell asks two new questions plus any prompt you type into `CUSTOM_PROMPT`, validated first through "
                "`validate_prompts` (the same checks `generate` applies: non-empty turns, the `MAX_NEW_TOKENS_CEILING` and the "
                "rendered-token ceiling), and shows the base and adapted answers side by side by switching the adapter off "
                "and on (`model.disable_adapter()`) — the cleanest way to see what the adapter alone contributes. Watch for "
                "language and register (did it stay in Filipino?), whether it stops cleanly, and repetition loops, the "
                "classic sign of a small model pushed too hard by greedy decoding. Real products should sample "
                "(`do_sample=True, temperature=0.7, top_p=0.8, top_k=20`); greedy is for reproducible checks.\n\n"
                "**Predict:** for a prompt the adapter never saw, will the adapted answer stay in Filipino more often than the base answer?\n\n"
                "**What to notice:** compare each BASE/ADAPTED pair on language, length and whether it stops cleanly; a "
                "repeated phrase is a greedy-decoding loop, not a training bug.\n\n"
                "<details><summary>Check your reasoning</summary>\n\n"
                "Often, but not always: about a hundred training rows shift the *style* of answers, so expect some prompts to "
                "change register or language and others to look much like the base. Neither column is scored; this is "
                "qualitative evidence.\n\n"
                "</details>"
            ),
            "code": (
                "RUN_NEW_PROMPT_INFERENCE = True  # @param {{type:\"boolean\"}}\n"
                "CUSTOM_PROMPT = ''  # @param {{type:\"string\"}}\n\n"
                "NEW_PROMPTS = [\n"
                "    'Sumulat ng maikling payo para sa isang estudyanteng nagsisimula sa AI.',\n"
                "    'Ipaliwanag ang pagkakaiba ng training data at evaluation data sa dalawang pangungusap.',\n"
                "]\n"
                "if CUSTOM_PROMPT.strip():\n"
                "    NEW_PROMPTS.append(CUSTOM_PROMPT.strip())\n"
                "new_prompt_manifest = validate_prompts(NEW_PROMPTS, 96, token_length=pipe.prompt_token_length)\n\n"
                "def base_and_adapted(prompt):\n"
                "    with model.disable_adapter():\n"
                "        base_answer = pipe.generate(prompt, model=model)\n"
                "    return base_answer, pipe.generate(prompt, model=model)\n\n"
                "new_prompt_rows = []\n"
                "if RUN_NEW_PROMPT_INFERENCE:\n"
                "    for prompt in NEW_PROMPTS:\n"
                "        base_answer, adapted_answer = base_and_adapted(prompt)\n"
                "        new_prompt_rows.append({{'prompt': prompt, 'base': base_answer, 'adapted': adapted_answer}})\n"
                "        print(f'PROMPT:  {{prompt}}\\nBASE:    {{base_answer}}\\nADAPTED: {{adapted_answer}}\\n')\n"
                "print({{'new_prompts': len(NEW_PROMPTS), 'rendered_tokens': [i['rendered_tokens'] for i in new_prompt_manifest['inputs']]}})"
            ),
        },
        {
            "md": (
                "### Activity (optional): greedy versus sampled decoding on the adapted model\n\n"
                "A runnable predict → change → run → observe → explain activity, **off by default** so that Run all is unchanged. "
                "Set `RUN_DECODING_EXPERIMENT = True` and re-run this cell, at any time after Section 7 (the trained model stays in "
                "memory after a full run). It asks the first new prompt once with the greedy rule and twice with the direct-answer "
                "sampling settings (`temperature=0.7, top_p=0.8, top_k=20`), each draw seeded with `SEED` and `SEED + 1` so you can "
                "reproduce it, and counts the longest run of a repeated 4-word phrase in each answer — the signature of a greedy "
                "loop.\n\n"
                "**Predict:** which answer is most likely to loop? Will the two sampled answers be identical? Will changing `SEED` "
                "change the greedy answer?\n\n"
                "<details><summary>Check your reasoning</summary>\n\n"
                "The greedy answer, if any: it always takes the most likely token, so once a phrase becomes the most likely "
                "continuation of itself it repeats. The sampled answers usually differ from each other (two draws can coincide, "
                "but rarely over 96 tokens) and loop less. Changing `SEED` changes the sampled answers only; the greedy answer "
                "depends on the weights, not the seed.\n\n"
                "</details>"
            ),
            "code": (
                "RUN_DECODING_EXPERIMENT = False  # @param {{type:\"boolean\"}}\n\n\n"
                "def longest_repeat(text, n=4):\n"
                "    \"\"\"How many times the most repeated n-word phrase occurs: 1 means no repetition.\"\"\"\n"
                "    words = text.split()\n"
                "    phrases = [' '.join(words[i:i + n]) for i in range(max(0, len(words) - n + 1))]\n"
                "    return max((phrases.count(p) for p in set(phrases)), default=1)\n\n\n"
                "if RUN_DECODING_EXPERIMENT:\n"
                "    SAMPLING = {{'do_sample': True, 'temperature': 0.7, 'top_p': 0.8, 'top_k': 20}}\n"
                "    experiment_prompt = NEW_PROMPTS[0]\n"
                "    decoding_rows = [('greedy', pipe.generate(experiment_prompt, model=model))]\n"
                "    for attempt in range(2):\n"
                "        torch.manual_seed(SEED + attempt)\n"
                "        decoding_rows.append((f'sampled (seed {{SEED + attempt}})', pipe.generate(experiment_prompt, model=model, **SAMPLING)))\n"
                "    print(f'PROMPT: {{experiment_prompt}}\\n')\n"
                "    for kind, answer in decoding_rows:\n"
                "        print(f'{{kind}}: longest repeated 4-word phrase occurs {{longest_repeat(answer)}}x | {{answer}}\\n')\n"
                "    print({{'sampled_answers_identical': decoding_rows[1][1] == decoding_rows[2][1]}})\n"
                "else:\n"
                "    print('RUN_DECODING_EXPERIMENT is off: set it to True and re-run this cell to compare greedy and seeded sampled answers on the adapted model.')"
            ),
        },
        {
            "md": (
                "## 10. Export the adapter bundle, prove a fresh reload, and write outputs\n\n"
                "The deliverable is the **adapter bundle**, not a copy of the base model: `pipe.export_adapter_bundle` writes "
                "the LoRA matrices (`adapter_model.safetensors`), the adapter config, the tokenizer with its chat template (so "
                "inference renders prompts exactly as training did), `metrics.json`, `provenance.json` (base model id and "
                "pinned revision, dataset digest and licence, hyperparameters, runtime) and an `artifact-manifest.json` "
                "listing every file with its size and SHA-256. No training rows are written into the bundle. Adapter "
                "artifacts depend on the base model and are **not complete models by themselves**.\n\n"
                "Then the notebook checks what the bundle reproduces **from disk**: it loads the base model a second time from the "
                "digest-verified snapshot of Section 3 (`pipe.reload_base`, no network) into a *separate* object — the trained "
                "model stays in memory, so Section 9 can still be re-run — and attaches the saved adapter to it through "
                "`pipe.load_adapter`, which re-verifies the bundle before any state is deserialised. Three hard checks follow: "
                "the reloaded `B` matrices are not all zero, the adapter-off answer differs from the adapter-on answer (so the "
                "deltas are really applied), and a fresh prompt generates something. Then comes the part a consumer cares "
                "about: **does the artifact reproduce the reported numbers?** The reloaded model is scored on the same "
                "validation split and its 16-token greedy opening is compared with the in-memory one. The two models are not "
                "numerically identical by construction: `prepare_model_for_kbit_training` upcast the trained model's "
                "non-quantized layers (embeddings, norms, the tied output head) to float32, while the reloaded base runs in the "
                "compute dtype Section 3 chose, so a small loss difference is expected and greedy openings can diverge after a "
                "near-tie. The cell reports the reloaded validation loss, the absolute difference against a stated tolerance, "
                "and whether the openings are identical, and names what was and was not reproduced. Finally the machine-readable "
                "result JSON (metrics including the reload check, report, input manifest, sample identity and digest, "
                "hyperparameters, the notebook's source, the model identity, licence and runtime) and the before/after probe "
                "table (CSV, one row per prompt) are written, and the bundle is zipped for the companion artifact-inference "
                "notebook, which refuses any bundle whose files do not match the manifest. On Colab the ZIP is offered as a "
                "download; elsewhere the cell prints where to find it, with its SHA-256.\n\n"
                "**Predict:** which files will the bundle list, and will any training row be inside it? Will the reloaded "
                "validation loss equal the in-memory one exactly?\n\n"
                "<details><summary>Check your reasoning</summary>\n\n"
                "The adapter weights and config, the tokenizer, `metrics.json`, `provenance.json` and the "
                "`artifact-manifest.json` that lists every file with its size and SHA-256 — and no training rows. The reloaded "
                "loss is usually close but not bit-identical, because the reloaded base keeps its non-quantized layers in the "
                "compute dtype while training upcast them to float32; the cell says whether the difference sits inside the "
                "stated tolerance and whether the greedy openings matched. `PASS` names the checks that held; a reload whose "
                "loss falls outside the tolerance is reported as **not reproduced**, not hidden.\n\n"
                "</details>"
            ),
            "code": (
                "import csv\n"
                "import zipfile\n\n"
                "ADAPTER_DIR = Path('outputs') / 'adapter-bundle'\n"
                "ARTIFACT_ZIP = Path('outputs') / '{stem}_adapter_bundle.zip'\n"
                "PROVENANCE = {{\n"
                "    'datasetDigest': DATASET_DIGEST,\n"
                "    'dataset': DATASET_PROVENANCE,\n"
                "    'training': {{'method': TRAINING_METHOD, 'epochs': EPOCHS, 'exportedEpoch': EPOCHS, 'epochSelection': 'last epoch; no selection by validation loss', 'learningRate': LEARNING_RATE, 'loraRank': LORA_RANK, 'loraAlpha': LORA_ALPHA, 'targetModules': LORA_TARGETS, 'maxSequenceLength': MAX_SEQUENCE_LENGTH, 'gradAccum': GRAD_ACCUM, 'seed': SEED, 'nonQuantizedLayersTrainedIn': 'float32 (prepare_model_for_kbit_training upcast)'}},\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'peft': importlib.metadata.version('peft'), 'gpu': GPU_NAME, 'gpuVramGiB': GPU_VRAM_GB, 'computeDtype': pipe.compute_dtype, 'quantized4bit': pipe.quantized}},\n"
                "    'notebookSource': NOTEBOOK_SOURCE,\n"
                "}}\n"
                "bundle_manifest = pipe.export_adapter_bundle(model, ADAPTER_DIR, metrics=METRICS, provenance=PROVENANCE)\n"
                "print({{'bundle': str(ADAPTER_DIR), 'files': [f['path'] for f in bundle_manifest['files']], 'total_bytes': bundle_manifest['totalBytes']}})\n\n"
                "# Fresh base + adapter reload, from disk, into a SEPARATE object: the trained `model` stays usable (Section 9 can be re-run).\n"
                "REPLAY_TOKENS = 16\n"
                "RELOAD_LOSS_TOLERANCE = 0.05  # nats per supervised token; the trained model ran its non-quantized layers in float32, the reloaded one in the compute dtype\n"
                "expected_opening = pipe.generate(PROMPTS[0], model=model, max_new_tokens=REPLAY_TOKENS)\n"
                "reloaded = pipe.load_adapter(ADAPTER_DIR, base_model=pipe.reload_base())\n"
                "lora_b_matrices = [param for name, param in reloaded.named_parameters() if 'lora_b' in name.lower()]\n"
                "if not lora_b_matrices or max(p.abs().max().item() for p in lora_b_matrices) == 0:\n"
                "    raise RuntimeError('Reloaded adapter weights are zero or missing')\n"
                "reloaded_opening = pipe.generate(PROMPTS[0], model=reloaded, max_new_tokens=REPLAY_TOKENS)\n"
                "with reloaded.disable_adapter():\n"
                "    adapter_off_opening = pipe.generate(PROMPTS[0], model=reloaded, max_new_tokens=REPLAY_TOKENS)\n"
                "if reloaded_opening == adapter_off_opening:\n"
                "    raise RuntimeError('Reloaded adapter has no effect: adapter-on and adapter-off answers are identical')\n"
                "smoke = pipe.generate('Kumusta! Sagutin sa isang maikling pangungusap.', model=reloaded, max_new_tokens=32)\n"
                "if not smoke:\n"
                "    raise RuntimeError('Fresh reload generated nothing')\n"
                "# What the artifact reproduces: the validation loss (same rows, same units) within a stated tolerance, and the greedy opening exactly.\n"
                "reloaded_validation_loss = pipe.evaluate_loss(MASKED['validation'], model=reloaded)\n"
                "loss_abs_delta = abs(reloaded_validation_loss - validation_loss)\n"
                "RELOAD_CHECK = {{\n"
                "    'in_memory_validation_loss': validation_loss,\n"
                "    'reloaded_validation_loss': reloaded_validation_loss,\n"
                "    'validation_loss_abs_delta': loss_abs_delta,\n"
                "    'tolerance': RELOAD_LOSS_TOLERANCE,\n"
                "    'loss_reproduced_within_tolerance': loss_abs_delta <= RELOAD_LOSS_TOLERANCE,\n"
                "    'greedy_openings_identical': reloaded_opening == expected_opening,\n"
                "    'in_memory_non_quantized_dtype': 'float32 (prepare_model_for_kbit_training upcast)',\n"
                "    'reloaded_non_quantized_dtype': pipe.compute_dtype,\n"
                "}}\n"
                "METRICS['reloadedValidationLoss'] = reloaded_validation_loss\n"
                "METRICS['reloadedValidationPerplexity'] = perplexity(reloaded_validation_loss)\n"
                "reproduced = 'reproduced' if RELOAD_CHECK['loss_reproduced_within_tolerance'] else 'NOT reproduced'\n"
                "openings = 'identical' if RELOAD_CHECK['greedy_openings_identical'] else 'differ (a near-tie flipped under the dtype difference; see the prose)'\n"
                "print(f'PASS: fresh base + adapter reload from the verified snapshot; adapter weights present and active. Reloaded validation loss {{reloaded_validation_loss:.4f}} vs in-memory {{validation_loss:.4f}} (|difference| {{loss_abs_delta:.4f}}, tolerance {{RELOAD_LOSS_TOLERANCE}}): {{reproduced}}. Greedy {{REPLAY_TOKENS}}-token openings: {{openings}}.')\n"
                "print({{'in_memory_adapted_opening': expected_opening, 'reloaded_adapted_opening': reloaded_opening, 'reloaded_adapter_off': adapter_off_opening, 'fresh_prompt': smoke}})\n\n"
                "with zipfile.ZipFile(ARTIFACT_ZIP, 'w', zipfile.ZIP_STORED) as archive:\n"
                "    for path in sorted(ADAPTER_DIR.rglob('*')):\n"
                "        if path.is_file():\n"
                "            archive.write(path, path.relative_to(ADAPTER_DIR).as_posix())\n"
                "payload = {{\n"
                "    'metrics': METRICS,\n"
                "    'evaluation_report': report,\n"
                "    'input_manifest': input_manifest,\n"
                "    'new_prompt_manifest': new_prompt_manifest,\n"
                "    'probes': probes,\n"
                "    'new_prompts': new_prompt_rows,\n"
                "    'reload': {{**RELOAD_CHECK, 'in_memory_opening': expected_opening, 'reloaded_opening': reloaded_opening, 'adapter_off_opening': adapter_off_opening, 'fresh_prompt': smoke, 'replay_tokens': REPLAY_TOKENS}},\n"
                "    'sample': {{'kind': sample_kind, 'name': data_name, 'splits': {{name: len(records) for name, records in SPLITS.items()}}, 'dataset_digest': DATASET_DIGEST, 'provenance': DATASET_PROVENANCE}},\n"
                "    'artifact': {{'bundle_dir': str(ADAPTER_DIR), 'zip': str(ARTIFACT_ZIP), 'zip_sha256': sha256_of_file(ARTIFACT_ZIP), 'manifest': bundle_manifest}},\n"
                "    'training': PROVENANCE['training'],\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'runtime': {{**PROVENANCE['runtime'], 'device': pipe.device, 'quantized_4bit': pipe.quantized, 'compute_dtype': pipe.compute_dtype}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(payload, handle, indent=2, ensure_ascii=False)\n"
                "with open('outputs/{stem}_probes.csv', 'w', encoding='utf-8', newline='') as handle:\n"
                "    writer = csv.writer(handle)\n"
                "    writer.writerow(['stage', 'prompt', 'base', 'adapted'])\n"
                "    for row in probes:\n"
                "        writer.writerow(['evaluation-probe', row['prompt'], row['base'], row['adapted']])\n"
                "    for row in new_prompt_rows:\n"
                "        writer.writerow(['new-prompt', row['prompt'], row['base'], row['adapted']])\n"
                "print(f\"Artifact: {{ARTIFACT_ZIP}} ({{ARTIFACT_ZIP.stat().st_size / 1024**2:.1f}} MB) SHA-256 {{payload['artifact']['zip_sha256']}}\")\n"
                "print(sorted(os.listdir('outputs')))\n"
                "try:\n"
                "    from google.colab import files\n"
                "    files.download(str(ARTIFACT_ZIP))\n"
                "except (ImportError, AttributeError):\n"
                "    print(f'No download dialog in this runtime: the bundle ZIP is at {{ARTIFACT_ZIP.resolve()}}')"
            ),
        },
    ],
    "closing": (
        "## Interpretation and limits\n\n"
        "The adapter changes *how* the pinned base model answers — language, register, format — on the distribution of the "
        "training rows; it does not add knowledge or make the model correct. `validationLoss` and `validationPerplexity` in "
        "the evaluation report are optimisation evidence on a validation split manufactured from the training source "
        "(verdict `sample-sanity`), not task quality: do not ship on perplexity; read them against `baseValidationLoss`, the same split scored before adaptation. The reload check in Section 10 says which numbers the exported artifact reproduces and within what tolerance. The before/after and new-prompt tables are "
        "qualitative; they show a shift, not an improvement. Training on very few rows, raising the epoch count, or a "
        "learning rate above `2e-4` all overfit quickly and degrade general behaviour in ways the metrics above do not "
        "measure; greedy decoding can loop on small models. Adapters trained on `Sample: Dolly` inherit CC-BY-SA 3.0; BYOD "
        "adapters inherit your data's licence and confidentiality obligations, and `provenance.json` records the dataset "
        "digest so that lineage is traceable.\n\n"
        "Successful execution proves that the recorded repository revision's pipeline module, carried in this notebook, can "
        "acquire and digest-verify the pinned base snapshot, validate the demonstrated dataset, render and mask it with the "
        "model's own chat template, execute a QLoRA adaptation with per-token train and validation loss, generate with the "
        "adapter off and on, export a manifested adapter bundle, and reconstruct it from disk against the verified base with a stated reproduction check — "
        "without the repository being reachable. It does **not** establish benchmark superiority, task quality on your "
        "domain, safety, fairness, or production fitness.\n\n"
        "## Troubleshooting\n\n"
        "Section 1 stops with `This notebook needs a Linux x86_64 runtime`: use Google Colab, Kaggle or a Linux Jupyter host. "
        "`The pinned uv wheel failed its size/SHA-256 check`: run Section 1 again; if it repeats, the download is being "
        "altered. `The isolated environment's Python process exited`: the worker crashed, usually out of GPU or host memory — "
        "restart the session and choose **Run all**. `No GPU visible` in Section 4: select a T4 GPU runtime and run all again. "
        "`CUDA out of memory` in Section 7: lower `MAX_SEQUENCE_LENGTH` or `SAMPLE_LIMIT`. A leakage `ValueError` from "
        "`validate_inputs` on your own data: the same record appears in two files — remove the duplicate. `BYOD requires "
        "train.jsonl`, `… line N: not a messages … record`, `BYOD_PATH … is neither a folder nor a .zip file` or `The upload "
        "was cancelled or empty`: fix the named file or path and re-run from Section 4. `Reloaded adapter has no effect` in "
        "Section 10: the adapter learned almost nothing — check `LEARNING_RATE` and `EPOCHS`. `NOT reproduced` in the Section 10 "
        "reload line: the reloaded artifact's validation loss differs from the in-memory one by more than the tolerance — record "
        "both numbers; the artifact's own number is the one a consumer will see. `No download dialog in this runtime`: fetch the "
        "ZIP from the printed path. `NameError` after editing a form field: re-run from Section 4 (every later cell depends on it) "
        "— only Section 9 and the decoding activity can be re-run on their own after a full run.\n\n"
        "## Change one thing (next experiments)\n\n"
        "Switch on the decoding activity after Section 9 and compare greedy with seeded sampling; set `EPOCHS = 3` and watch whether the "
        "validation loss keeps falling or turns up (overfitting — every epoch is recorded, the last one is exported); "
        "raise `LORA_RANK` to 16 with `LORA_ALPHA` 32 and compare loss and answers; switch to `Sample: Dolly` and see the "
        "`set aside` count grow with a 512-token window; enable `USE_BYOD` with a few hundred rows from your own task and "
        "score the adapter against your own held-out set; feed `outputs/{stem}_adapter_bundle.zip` to the companion "
        "artifact-inference notebook in a separate session. Re-run from Section 6 after any change: the cells restart from the "
        "frozen base.\n\n"
        "## Glossary\n\n"
        "- **Token:** the unit the model reads and writes — a word piece; sequence lengths and ceilings are counted in tokens.\n"
        "- **Chat template:** the base tokenizer's rule for turning a list of `{{role, content}}` turns into one token sequence with role markers.\n"
        "- **SFT (supervised fine-tuning):** training on example conversations so the model imitates the assistant turns.\n"
        "- **Assistant-only loss masking:** every token outside an assistant turn gets label `-100` (`IGNORE_INDEX`), so only the answers are learned.\n"
        "- **LoRA:** a trainable low-rank correction `B A` added to a frozen weight matrix; `B` starts at zero, so training starts from the base model.\n"
        "- **QLoRA / `nf4`:** LoRA on a base model stored in 4-bit NormalFloat, dequantized on the fly; it is what makes a T4 enough.\n"
        "- **Adapter bundle:** the LoRA weights plus tokenizer, metrics, provenance and a SHA-256 manifest; useless without the exact base model it was trained on.\n"
        "- **Validation loss / perplexity:** average per-token loss on held-out rows, and its exponential; optimisation evidence, not answer correctness.\n"
        "- **Manufactured validation split:** rows held out from the training source itself, so it measures fit to that source, not to your task.\n"
        "- **Gradient accumulation:** summing gradients over several examples before one optimizer step (`GRAD_ACCUM = 2`).\n"
        "- **Greedy decoding:** always taking the most likely next token; reproducible, but small models can loop.\n"
        "- **Base validation loss:** the unadapted model's loss on the same validation split, recorded before training; the number the adapted loss is read against.\n"
        "- **Reload check:** scoring the reloaded artifact on the same split and comparing its greedy opening with the in-memory model's, so \"loads\" is not mistaken for \"reproduces\".\n"
        "- **Isolated environment:** the separate hash-locked Python environment built in Section 1; every later cell runs there.\n\n"
        "## Conclusion (your notes)\n\n"
        "1. In two sentences: what did the adapter change — in the validation loss against the base model's, and in the answers — and what evidence do you have for it?\n"
        "2. Why is the validation loss in the evaluation report not a measure of answer quality?\n"
        "3. Which of your predictions were wrong, and what did the output show instead?\n"
        "4. What would you need before deploying an adapter trained this way on your own task?\n\n"
        "**Your notes:**\n\n"
        "## References\n\n"
        f"- Repository README: https://github.com/kurtvalcorza/{REPO}/blob/main/README.md\n"
        f"- Repository model card: https://github.com/kurtvalcorza/{REPO}/blob/main/weights/smollm2-360m/MODEL_CARD.md\n"
        f"- Weight provenance: https://github.com/kurtvalcorza/{REPO}/blob/main/weights/README.md\n"
        f"- Artifact-inference companion: https://github.com/kurtvalcorza/{REPO}/blob/main/tutorials/language_model_artifact_inference_colab.ipynb\n"
        "- Upstream model: https://huggingface.co/{MODEL_ID}\n"
        "- Upstream code: https://github.com/huggingface/smollm\n"
        "- SmolLM2 paper: https://arxiv.org/abs/2502.02737\n"
        "- QLoRA: https://arxiv.org/abs/2305.14314\n"
        "- LoRA: https://arxiv.org/abs/2106.09685"
    ),
}
